### ISSUE TITLE
NHDDL not working with udpbd-vexfat (SCPH-90008)

### ISSUE THREAD

**Issue by 10522** [pcm720/nhddl#5]
NHDDL 0.3.0 + Neutrino 20240902 + udpbd-vexfat 0.2.0 - Freezes on a black screen
NHDDL 0.2.0 + Neutrino 20240902 + udpbd-vexfat 0.2.0 - Freezes on this screen:

![errr](https://github.com/user-attachments/assets/f914bada-e339-4625-a921-260c29e0e29f)

Is it possible to add support for [udpbd-vexfat](https://github.com/awaken1ng/udpbd-vexfat) (read-only works) and also running NHDDL via USB (not just via MC)?

@pcm720 @awaken1ng

**Comment by pcm720** [comment]
The latest NHDDL release works fine with `udpbd-vexfat` when it's hosted from my Linux machine.
Sure, NHDDL is unable to write title cache to the hosted folder due to `udpbd-vexfat` mounting it read-only, but it certainly doesn't break it.

There's not enough details in your post for me to come to any conclusion.
What do you mean by "freezes on a black screen"? Does it happen before or after title list screen?

> running NHDDL via USB (not just via MC)?

No. there are currently no plans to support this use case, as I don't use USB storage on my PS2 and don't have the time to support it in a way I'm happy with.

**Comment by pcm720** [comment]
I've replicated your folder structure and run a couple of tests.
My limited testing shows thatBDM disconnects after NHDDL attempts to write to it when using udpbd-vexfat on Windows. The debug output shows:
` BDM: disconnecting device udp0p0 id=0x0`
This also occurs when the UDPBD server is shut down manually with Ctrl+C.

I also couldn't replicate this behavior on Linux, regardless of how many times I launched NHDDL.
So I don't consider this a NHDDL problem, as read-only BDM devices is not something NHDDL supports.
So, my advice is to either:
 - Use a different UDPBD server on Windows
 - Host udpbd-vexfat from Linux machine

**Comment by pcm720** [comment]
> Is it possible to implement read-only: 1 in nhddl.yaml or make the nhddl directory saved on USB or MC when using udpbd-vexfat?

Sorry, but I'm not going to implement a workaround for something that fails only on one particular piece of software running on one particular operating system.
Like I said, writing to `udpbd-vexfat` on Linux fails silently and doesn't close the connection. `udpbd-vexfat` must either fail silently on Windows too or return an error when requested to open the file with write permissions.
